### PR TITLE
Upgrade to net6.0 to prevent dependency issues after upgrading MSBuild.Locator

### PR DESCRIPTION
**Pull request by carlossanlop**
Related to https://github.com/carlossanlop/DocsPortingTool/pull/40
cc @safern @ericstj

### CODE REVIEW

**Comment by carlossanlop** [comment]
The CI fails with: `The current .NET SDK does not support targeting .NET 6.0.`. Do you know if .NET 6.0 can be used officially in GitHub CI?

**Comment by ericstj** [comment]
Did you make a change to your global.json to pre-requisite this version?  Does your repo use Arcade?  That should acquire a CLI for building based on global.json contents.

**Comment by safern** [comment]
> Does your repo use Arcade? That should acquire a CLI for building based on global.json contents.

No it doesn't use arcade, but we should add a global.json file with a rollForward policy.

**Comment by carlossanlop** [comment]
The CI error is weird. I assume it's saying it didn't recognize `6.0.x` as a .NET version?

**Comment by safern** [comment]
I can't push to this branch. The CI error is because when the latest version available in the releases-json index is a preview version, their semver check is failing. So you either need to specify an exact version i.e the full preview version of the SDK or since we need to add a global.json file anyway, don't include a version and that will fallback to the global.json specified version.

Here is a PR to fix that issue in their action by taking an `include prerelease` parameter: https://github.com/actions/setup-dotnet/pull/110

I put up a PR because I can't push to your branch which adds global.json and the build is green. https://github.com/carlossanlop/DocsPortingTool/pull/46

**Pull request merged**
