### PR TITLE
Tweak logging

### PR DESCRIPTION
**Pull request by danmoseley**
Some minor tweaks to logging I made that I found useful while working with this.

### CODE REVIEW

**Comment by danmoseley** [comment]
@carlossanlop

**Comment by danmoseley** [comment]
No idea what's going on here. Will have to look later.
```
System.IO.FileLoadException: Could not load file or assembly 'NuGet.Frameworks, Version=6.0.0.179, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (0x80131621)
File name: 'NuGet.Frameworks, Version=6.0.0.179, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
 ---> System.IO.FileLoadException: Could not load file or assembly 'NuGet.Frameworks, Version=6.0.0.179, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
```

**Comment by carlossanlop** [comment]
> No idea what's going on here. Will have to look later.

Unrelated to your change. Known issue in the backporting logic. I have yet to find a way to make it work with .NET 6.0.

**Comment by carlossanlop** [comment]
Thanks!

**Pull request merged**
